#include <CL/sycl.hpp>
#include <convolution.hpp>


int main(){

  // Define input parameters
  size_t input_width = 32;
  size_t input_height = 32;
  size_t input_depth = 3;
  
  // Create a random input volume
  Volume input_volume = rand_volume_generator(input_width,input_height,input_depth);
  print_volume(input_volume);
  
  // Create a convolver object; weights are generated by a stub method
  convolver c33(generate_stub_weights(3,input_depth,4),1);
  c33.convolve(input_volume);
  
  convolver c55(generate_stub_weights(5,input_depth,2),1);
  c55.convolve(input_volume);
  
  convolver p22(2,1);
  p22.pool(input_volume);
  
  std::cout << "Finished" << std::endl;
  return 0;
};
