#include <CL/sycl.hpp>
#include <convolution.hpp>


int main(){
  size_t input_width = 32;
  size_t input_height = 32;
  size_t input_depth = 3;
  Volume input_volume = rand_volume_generator(input_width,input_height,input_depth);
  print_volume(input_volume);
  convolver c(input_volume);
  std::vector<Volume> weights;
  int filter_number = 4;
  // Weights are generated by a stub method
  for (int i=1; i<=filter_number; i++){
    Volume w =generate_stub_weights(3,input_depth,float(i));
    weights.push_back(w);
  }
  c.convolve(weights,3,1,1,filter_number);
  std::cout << "finished" << std::endl;
  return 0;
};
